"""Baseline LMS schema

Creates the `lms` schema and all 14 tables from the SQLAlchemy metadata.

Why metadata-driven rather than hand-written `op.create_table` calls: this is
the *baseline* revision, so building it from `Base.metadata` guarantees the
migrated database and the models cannot drift at the starting point. CI runs
`alembic upgrade head` followed by `alembic check`, which fails the build if
the two ever disagree. Every revision *after* this one is a normal
autogenerated diff.

Revision ID: 0001
Revises:
Create Date: 2026-09-14

"""
from typing import Sequence, Union

from alembic import op

from app.db.base_class import DB_SCHEMA
from app.models import Base

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    connection = op.get_bind()

    if DB_SCHEMA:
        op.execute(f'CREATE SCHEMA IF NOT EXISTS "{DB_SCHEMA}"')

    # pgcrypto gives us gen_random_uuid() for server-side defaults and any
    # future column-level encryption of PII.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    Base.metadata.create_all(bind=connection, checkfirst=True)


def downgrade() -> None:
    connection = op.get_bind()
    Base.metadata.drop_all(bind=connection, checkfirst=True)
    if DB_SCHEMA:
        op.execute(f'DROP SCHEMA IF EXISTS "{DB_SCHEMA}" CASCADE')
